export enum Events {
    SENDMESSAGE = 'SENDMESSAGE',
    NEWMESSAGE = 'NEWMESSAGE',
    NEWUSER = 'NEWUSER',
    SETUSER = 'SETUSER',
    REMOVEUSER = 'REMOVEUSER',
    UPDATEUSERLIST = 'UPDATEUSERLIST',
    OFFUSER = 'OFFUSER'
}